export const toolsRowLeft = [
  { name: "Figma", href: "https://www.figma.com", slug: "figma" },
  { name: "Claude", href: "https://claude.ai", slug: "anthropic" },
  { name: "Balsamiq", href: "https://balsamiq.com", slug: "balsamiq" },
  { name: "ChatGPT", href: "https://chatgpt.com", slug: "openai" },
  { name: "Canva", href: "https://www.canva.com", slug: "canva" },
  { name: "Gemini", href: "https://gemini.google.com", slug: "googlegemini" },
  { name: "Photoshop", href: "https://www.adobe.com/products/photoshop.html", slug: "adobephotoshop" },
  { name: "Cursor", href: "https://cursor.com", slug: "cursor" },
  { name: "Illustrator", href: "https://www.adobe.com/products/illustrator.html", slug: "adobeillustrator" },
  { name: "Composio", href: "https://www.composio.dev", slug: null },
  { name: "Firefly", href: "https://www.adobe.com/products/firefly.html", slug: "adobe" },
  { name: "Make", href: "https://www.make.com", slug: "make" },
  { name: "Midjourney", href: "https://www.midjourney.com", slug: "midjourney" },
  { name: "Visily", href: "https://www.visily.ai", slug: null },
  { name: "Google Stitch", href: "https://stitch.withgoogle.com", slug: "google" },
];

export const toolsRowRight = [
  { name: "HTML", href: "https://developer.mozilla.org/en-US/docs/Web/HTML", slug: "html5" },
  { name: "Asana", href: "https://asana.com", slug: "asana" },
  { name: "CSS", href: "https://developer.mozilla.org/en-US/docs/Web/CSS", slug: "css" },
  { name: "Notion", href: "https://www.notion.so", slug: "notion" },
  { name: "JavaScript", href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript", slug: "javascript" },
  { name: "Trello", href: "https://trello.com", slug: "trello" },
  { name: "WordPress", href: "https://wordpress.org", slug: "wordpress" },
  { name: "Mailchimp", href: "https://mailchimp.com", slug: "mailchimp" },
  { name: "Elementor", href: "https://elementor.com", slug: "elementor" },
  { name: "Outlook", href: "https://www.microsoft.com/microsoft-365/outlook", slug: "microsoftoutlook" },
  { name: "Divi", href: "https://www.elegantthemes.com/gallery/divi/", slug: null },
  { name: "Teams", href: "https://www.microsoft.com/microsoft-teams", slug: "microsoftteams" },
  { name: "Payload", href: "https://payloadcms.com", slug: "payloadcms" },
  { name: "Loop", href: "https://www.microsoft.com/microsoft-365/loop", slug: "microsoft" },
  { name: "GitHub", href: "https://github.com", slug: "github" },
  { name: "Office", href: "https://www.microsoft.com/microsoft-365", slug: "microsoft365" },
  { name: "Vercel", href: "https://vercel.com", slug: "vercel" },
  { name: "Workspace", href: "https://workspace.google.com", slug: "google" },
];
