export const toolCategories = [
  "All",
  "Design",
  "Development",
  "AI & Automation",
  "Workflow & Ops",
];

export const tools = [
  { name: "Figma", href: "https://www.figma.com", slug: "figma", category: "Design" },
  { name: "Balsamiq", href: "https://balsamiq.com", slug: null, category: "Design" },
  { name: "Google Stitch", href: "https://stitch.withgoogle.com", slug: "google", category: "Design" },
  { name: "Visily", href: "https://www.visily.ai", slug: null, category: "Design" },
  { name: "Canva", href: "https://www.canva.com", slug: null, category: "Design" },
  { name: "Photoshop", href: "https://www.adobe.com/products/photoshop.html", slug: null, category: "Design" },
  { name: "Illustrator", href: "https://www.adobe.com/products/illustrator.html", slug: null, category: "Design" },
  { name: "Firefly", href: "https://www.adobe.com/products/firefly.html", slug: "adobe", category: "Design" },
  { name: "Midjourney", href: "https://www.midjourney.com", slug: null, category: "Design" },
  { name: "HTML", href: "https://developer.mozilla.org/en-US/docs/Web/HTML", slug: "html5", category: "Development" },
  { name: "CSS", href: "https://developer.mozilla.org/en-US/docs/Web/CSS", slug: "css", category: "Development" },
  { name: "JavaScript", href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript", slug: "javascript", category: "Development" },
  { name: "WordPress", href: "https://wordpress.org", slug: "wordpress", category: "Development" },
  { name: "Elementor", href: "https://elementor.com", slug: "elementor", category: "Development" },
  { name: "Divi", href: "https://www.elegantthemes.com/gallery/divi/", slug: null, category: "Development" },
  { name: "Payload", href: "https://payloadcms.com", slug: "payloadcms", category: "Development" },
  { name: "GitHub", href: "https://github.com", slug: "github", category: "Development" },
  { name: "Vercel", href: "https://vercel.com", slug: "vercel", category: "Development" },
  { name: "Claude", href: "https://claude.ai", slug: null, category: "AI & Automation" },
  { name: "ChatGPT", href: "https://chatgpt.com", slug: null, category: "AI & Automation" },
  { name: "Gemini", href: "https://gemini.google.com", slug: "googlegemini", category: "AI & Automation" },
  { name: "Cursor", href: "https://cursor.com", slug: "cursor", category: "AI & Automation" },
  { name: "Composio", href: "https://www.composio.dev", slug: null, category: "AI & Automation" },
  { name: "Make", href: "https://www.make.com", slug: "make", category: "AI & Automation" },
  { name: "Asana", href: "https://asana.com", slug: "asana", category: "Workflow & Ops" },
  { name: "Notion", href: "https://www.notion.so", slug: "notion", category: "Workflow & Ops" },
  { name: "Trello", href: "https://trello.com", slug: "trello", category: "Workflow & Ops" },
  { name: "Mailchimp", href: "https://mailchimp.com", slug: "mailchimp", category: "Workflow & Ops" },
  { name: "Outlook", href: "https://www.microsoft.com/microsoft-365/outlook", slug: "microsoftoutlook", category: "Workflow & Ops" },
  { name: "Teams", href: "https://www.microsoft.com/microsoft-teams", slug: "microsoftteams", category: "Workflow & Ops" },
  { name: "Slack", href: "https://slack.com", slug: "slack", category: "Workflow & Ops" },
  { name: "Loop", href: "https://www.microsoft.com/microsoft-365/loop", slug: "microsoft", category: "Workflow & Ops" },
  { name: "Office", href: "https://www.microsoft.com/microsoft-365", slug: "microsoft365", category: "Workflow & Ops" },
  { name: "Google Workspace", href: "https://workspace.google.com", slug: "google", category: "Workflow & Ops" },
];
